import collapse from '@alpinejs/collapse';
import KoreOverlay from './overlay.js';
import KoreFeedback from './feedback.js';
import KoreSelect from './form/select.js';
import KoreInputOtp from './form/input-otp.js';
import KoreDatePicker from './form/datepicker.js';
import KoreUpload from './form/upload.js';
import KoreTimePicker from './form/time-picker.js';
import KoreRating from './form/rating.js';
import KoreRange from './form/range.js';
import KoreTagInput from './form/tag-input.js';
import KoreKeyValue from './form/key-value.js';
import KoreRepeater from './form/repeater.js';
import KoreColorPicker from './form/color-picker.js';
import KoreMaskable from './form/maskable.js';
import KorePassword from './form/password.js';
import KoreNumber from './form/number.js';
import KoreDropdown from './ui/dropdown.js';
import KoreAccordion from './ui/accordion.js';
import KoreTab from './ui/tab.js';
import KoreStepper from './ui/stepper.js';
import KoreStats from './ui/stats.js';
import KoreClipboard from './ui/clipboard.js';
import KoreSpeedDial from './ui/speed-dial.js';
import KoreSplitter from './ui/splitter.js';
import KoreChart from './ui/chart.js';
import KoreCarousel from './ui/carousel.js';
import KoreTree from './ui/tree.js';
import KoreTooltip from './ui/tooltip.js';
import KoreTransfer from './ui/transfer.js';
import KoreOrderList from './ui/order-list.js';
import KoreSidebar from './ui/sidebar.js';
import KoreDataTable from './datatable.js';
import KoreSpotlight from './spotlight.js';
import KoreTheme from './theme.js';
import KoreSidebarStore from './sidebar.js';

document.addEventListener('alpine:init', () => {
    Alpine.plugin(collapse);
    Alpine.data('KoreOverlay', KoreOverlay);
    Alpine.data('KoreFeedback', KoreFeedback);
    Alpine.data('KoreSelect', KoreSelect);
    Alpine.data('KoreInputOtp', KoreInputOtp);
    Alpine.data('KoreDatePicker', KoreDatePicker);
    Alpine.data('KoreUpload', KoreUpload);
    Alpine.data('KoreTimePicker', KoreTimePicker);
    Alpine.data('KoreRating', KoreRating);
    Alpine.data('KoreRange', KoreRange);
    Alpine.data('KoreTagInput', KoreTagInput);
    Alpine.data('KoreKeyValue', KoreKeyValue);
    Alpine.data('KoreRepeater', KoreRepeater);
    Alpine.data('KoreColorPicker', KoreColorPicker);
    Alpine.data('KoreMaskable', KoreMaskable);
    Alpine.data('KorePassword', KorePassword);
    Alpine.data('KoreNumber', KoreNumber);
    Alpine.data('KoreDropdown', KoreDropdown);
    Alpine.data('KoreAccordion', KoreAccordion);
    Alpine.data('KoreTab', KoreTab);
    Alpine.data('KoreStepper', KoreStepper);
    Alpine.data('KoreStats', KoreStats);
    Alpine.data('KoreClipboard', KoreClipboard);
    Alpine.data('KoreSpeedDial', KoreSpeedDial);
    Alpine.data('KoreSplitter', KoreSplitter);
    Alpine.data('KoreCarousel', KoreCarousel);
    Alpine.data('KoreChart', KoreChart);
    Alpine.data('KoreTree', KoreTree);
    Alpine.data('KoreTooltip', KoreTooltip);
    Alpine.data('KoreTransfer', KoreTransfer);
    Alpine.data('KoreOrderList', KoreOrderList);
    Alpine.data('KoreDataTable', KoreDataTable);
    Alpine.data('KoreSpotlight', KoreSpotlight);

    // El store se registra ANTES que el Alpine.data del sidebar: la factory
    // KoreSidebar llama a store.register() en su cuerpo, así que el store tiene
    // que existir ya cuando Alpine procese el primer x-data.
    Alpine.store('koreSidebar', KoreSidebarStore);
    Alpine.data('KoreSidebar', KoreSidebar);

    Alpine.store('koreTheme', KoreTheme);
});
